### ISSUE TITLE
Icons missing for tabs on Installation Page

### ISSUE THREAD

**Issue by nyuday** [getgauge/docs.gauge.org#119]
On this page, https://docs.gauge.org/latest/installation.html , icons for the following tabs are missing: 

1. Section: https://docs.gauge.org/latest/installation.html#install-gauge-for-your-os
Icons missing for: 
Freebsd, NPM

2. https://docs.gauge.org/latest/installation.html#uninstall-gauge . Icon missing for NPM

3. https://docs.gauge.org/latest/installation.html#ide-plugins. Icons missing for VS Code, Visual Studio . and IntelliJ

4. https://docs.gauge.org/latest/installation.html#reporting-plugins . HTML and XML report are missing icons. 

5.

**Comment by Debashis9012** [comment]
This has been verified and fixed in preview gauge portal.
