### ISSUE TITLE
Document how to set proxy server values for windows

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#127]
Our current document on setting [proxy servers](https://docs.gauge.org/latest/configuration.html#http-proxy) for plugin and template downloads only has instructions for Unix platforms (bash).

Add instructions for windows users.

**Comment by shubhamsc** [comment]
Configure http proxy for windows is added in [docs](https://docs.gauge.org/master/configuration.html#http-proxy)
