### ISSUE TITLE
Add an example to integrate gauge with azure pipeline

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/docs.gauge.org#136]
Gauge has some examples to integrate gauge with CI/CD.
https://docs.gauge.org/latest/howto/ci_cd/index.html#tutorials-integrating-gauge-with-ci-cd-tools
Add an example with Azure.

**Comment by Apoorva-GA** [comment]
Gauge and azure example has been added with this commit e236a62e8ef5fd4bd3d6138855784a258b1da377
