### ISSUE TITLE
Spike : Create buttons for `Select your OS, Language and IDE` with sphinx. 

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#147]
Also see
- How to keep this data throughout the app, cookie? Caching for that computer?

Refer : https://thoughtworks-products.invisionapp.com/share/ERSJFTTY2AU#/screens/369067852

**Comment by shubhamsc** [comment]
we can use query selector and local storage to persistent data across the pages. There is [sample project](https://github.com/shubhamsc/qs_spike) for this spike.
