### ISSUE TITLE
Spike : How to dynamically load content based on language, os and IDE

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#150]
When change filter is used to change language, OS, IDE options. Relevant page should be load dynamically.

**Comment by luciferankon** [comment]
Refer [here](https://github.com/luciferankon/dynamic_loading_promo/)

**Comment by Apoorva-GA** [comment]
Updated https://github.com/luciferankon/dynamic_loading_promo with the changes of spike.
