### ISSUE TITLE
Add getting started page - Creating a testing project page 

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#157]
https://thoughtworks-products.invisionapp.com/share/ERSJFTTY2AU#/screens/369070470

**Comment by luciferankon** [comment]
- [ ] Intellij
- [ ] Visual Studio

**Comment by Apoorva-GA** [comment]
Closing this as Visual Studio is tracked as a separate [issue](https://github.com/getgauge/docs.gauge.org/issues/170).
