### ISSUE TITLE
Add getting started page - `Viewing A Report` page

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#160]
https://thoughtworks-products.invisionapp.com/share/ERSJFTTY2AU#/screens/369559721

**Comment by luciferankon** [comment]
- [ ] Intellij
- [ ] Visual Studio

**Comment by Apoorva-GA** [comment]
Closing this as Visual Studio is tracked as a separate [issue](https://github.com/getgauge/docs.gauge.org/issues/170).
