### ISSUE TITLE
Fix Algolia search

### ISSUE THREAD

**Issue by nehashri** [getgauge/docs.gauge.org#176]
There are sections now in documentation which are shown based on some selections by user. Algolia search doesn't filter these sections based on the users selection.
However Algolia search should show contents that are relevant based on the user's selection.

**Comment by zabil** [comment]
This behaviour is fine. Algolia should show all the search results as the user could be searching for instructions on other platforms.

**Comment by nehashri** [comment]
Then, when the user clicks on that selection, we should show that section. As of now, the section will be hidden, so user will not see any content.
