### ISSUE TITLE
Ensure web content accessibility compliance (WCAG)

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#188]
Using the lighthouse extension for chrome 
- [x] Performance
- [x] Accessibility
- [x] Best Practices
    - https://github.com/getgauge/docs.gauge.org/issues/189 needs to be fixed
- [x] SEO

**Comment by luciferankon** [comment]
Performance for all the pages are in the range 85-91 and Accessibility, Best Practices and SEO is 100 for all the pages (except write a specification and run specification) for both mobile and desktop.
For those two pages, Performance is 81-83 and all other things are 100.
