### ISSUE TITLE
Search bar, header and improve this page alignment

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#192]
<img width="1016" alt="Screenshot 2019-08-21 at 14 29 47" src="https://user-images.githubusercontent.com/54427/63436266-4826a300-c420-11e9-86f1-7e05a20ac8f0.png">

The search bar, the header and "improve this page" must be aligned horizontally.

**Comment by Apoorva-GA** [comment]
Broken in CI/CD example pages. 
These pages should be consistent with other pages.

Example : https://docs-preview.gauge.org/howto/ci_cd/gocd.html?os=macos&language=java&ide=intellij

**Comment by Apoorva-GA** [comment]
I see the header twice. Also the header is coming up in the TOC.

<img width="1190" alt="Screenshot 2019-09-12 at 10 25 25 AM" src="https://user-images.githubusercontent.com/8462534/64755133-c837b880-d547-11e9-98d5-394d2f54418d.png">
