### ISSUE TITLE
Copy buttons not working

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#196]
- [x] Copy buttons on the code block are not working.
- [x] In Alternate installation methods section on getting started page, On click of copy button the section collapses which shouldn't happen.

**Comment by zabil** [comment]
This does not properly on 

* Browser Safari Version 12.1.2 (14607.3.9)

Click on any copy button for example on page https://docs-preview.gauge.org/getting_started/installing-gauge.html?os=macos&language=javascript&ide=vscode

and paste the text is getting copied as

```
brew install gaugeCopy copied
```

Instead of

```
brew install gauge
```
