### ISSUE TITLE
Correcting names and logos

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#198]
- [x] Csharp => C#
- [x] Intellij is not and editor, Intellij IDEA is.
- [x] VS Code => Visual Studio Code
- [x] use either monochrome or coloured logos for all. C# and Python are black.

**Comment by tinozza** [comment]
Find the updated logos for Python and C# in the[ google drive](https://drive.google.com/drive/folders/1zkSFkBxaD3oYVBS0OR_i41yDYdTWDBKe)


[icons.zip](https://github.com/getgauge/docs.gauge.org/files/3568437/icons.zip)
