### ISSUE TITLE
Updated  “In Page” ToC Styling

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#202]
Updated  “In Page” ToC Styling
- [ ] Refer styling on the Get Started Page  :https://zpl.io/VDWXAEW
- [x] Reduce the indent
- [x] Introduce hover behaviour ( yellow vertical line + bold text)
- [x] Remove bold text style
- [x] Change font color to #5e5e5e 
- [x] Font weight: regular

**Comment by tinozza** [comment]
Reference for ToC: https://zpl.io/VO1owDP
