### ISSUE TITLE
Need to Replace H1 tags with H2

### ISSUE THREAD

**Issue by veerababukona** [getgauge/docs.gauge.org#217]
1. Every page only one h1 tag is allowed, remaining need to be replaced with h2 or h3 according to the placement.

**Comment by Apoorva-GA** [comment]
Pages Involving this change : 

- [ ] Overview
- [ ] Get Started -  Installing Gauge
- [ ] Get Started - Create A Test Project
- [ ] Get Started - Running A Specification
- [ ] Get Started - Viewing Report
- [ ] Write Specifications
- [ ] Run Specifications
- [ ] Using Plugins
- [ ] Command Reference 
- [ ] Configuration
- [ ] Examples
- [ ] Faqs
- [ ] Troubleshooting Guide
- [ ] Gauge With Taiko
