### ISSUE TITLE
Text not wrapping in code blocks

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#227]
* Browser Safari Version 12.1.2 (14607.3.9)
* Code blocks

![Screenshot 2019-09-04 at 10 28 03](https://user-images.githubusercontent.com/54427/64243224-eaee1f80-cefe-11e9-811e-46426cac3186.png)

The text `The admin user must be able to search for available products on the search page
` is not wrapped correctly

**Comment by luciferankon** [comment]
What is the expected behavior? Should it break the words or should it make it scroll-able when overflowed.
