### ISSUE TITLE
Remove the outline boxes under "Reporting Plugins" section

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#236]
The outline boxes under the [reporting plugins](https://docs-preview.gauge.org/plugin.html?os=macos&language=javascript&ide=vscode#reporting-plugins) section is inconsistent with other sections

![Screenshot 2019-09-04 at 15 11 38](https://user-images.githubusercontent.com/54427/64263634-e12ce200-cf27-11e9-8f95-4455301a3c76.png)

Remove the box around the content and modify this to look like

#### HTML-Report

```
> gauge install html-report
```

For more information about XML-report generation plugin for Gauge, see Gauge GitHub for XML report generation

#### XML-Report

```
> gauge install xml-report
```

For more information about XML-report generation plugin for Gauge, see Gauge GitHub for XML report generation

**Comment by zabil** [comment]
Is there a commit that fixed this issue?

**Comment by Apoorva-GA** [comment]
This is the commit : dd57ad5c8cde61f8ba85374a70a624a1c4895bcf
