### ISSUE TITLE
Add a scroll horizontal scroll when the code block overflows

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#238]
In the page

https://docs-preview.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#how-to-add-a-parameter

![Screenshot 2019-09-04 at 15 56 28](https://user-images.githubusercontent.com/54427/64266599-c1e48380-cf2c-11e9-8a2e-57771ae26281.png)

Two issues here.

* The the code block does not have a horizontal scroll when it overflows
* The copy button alignment is broken

**Comment by BugDiver** [comment]
This issue matches with #263. @shubhamsc is already working on it. Added more details about this issue to #263. Closing it.
