### ISSUE TITLE
Test accessibility using taiko-accessibility plugin.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/docs.gauge.org#240]

**Comment by shubhamsc** [comment]
There are lots of violation error in docs site. I fixed for heading order, others still need to fixed.

Install taiko-accessibility plugin with taiko and jest.
Use this script to get the violation error
```
const { accessibility, closeBrowser, goto, openBrowser } = require('taiko');
const urls = require('./sitemaps').urls; //urls which need to be tested

describe('accessibility', () => {

    beforeEach(async () => {
        await openBrowser();
    });

    afterEach(async () => {
        await closeBrowser();
    });
    urls.forEach(url => {
        test(`Should be accessible for ${url}`, async () => {
            jest.setTimeout(20000);
            await goto(url);
            const audit = await accessibility.runAudit();
            expect(audit.score).toBeGreaterThan(85);
            expect(audit.violations.length).toEqual(0);
        });
    })

});
```

**Comment by BugDiver** [comment]
The test has been added in the `test` branch. To fix the violations some changes has been done (ex: change `div` -> `fieldset`, `h3` -> `legend` etc). These has some styling effect which needs to fixed before merging the branch. Most of the effect has been fixed but on the `getting_started/installing-gauge.html?` still some fix needs to be done.
