### ISSUE TITLE
Wrong font for "Gauge: Create new Project"

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#251]
Fix the font of "Gauge: Create new Project"
https://docs-preview.gauge.org/getting_started/create-test-project.html?os=macos&language=javascript&ide=vscode#step-1

![Screenshot 2019-09-05 at 13 24 11](https://user-images.githubusercontent.com/54427/64341647-b783c180-cfe0-11e9-9fd2-2c68ad0a51c5.png)

**Comment by Apoorva-GA** [comment]
Thats the font requirement given for highlighted text as per issue https://github.com/getgauge/docs.gauge.org/issues/204. 
Do we want to change this?

**Comment by Apoorva-GA** [comment]
Font should look like https://fonts.google.com/specimen/Source+Code+Pro which is not the case here. May be we need to load the font explicitly.
