### ISSUE TITLE
The permalinks for alternate installation methods not working

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#262]
Can't link to any of the alternate installation method permalinks for example

https://docs-preview.gauge.org/getting_started/installing-gauge.html?os=macos&language=javascript&ide=vscode#install-using-curl

This should go to the expanded section of curl installation method.
Also clicking on the permalink scrolls to the wrong location

![Screenshot 2019-09-06 at 15 31 09](https://user-images.githubusercontent.com/54427/64436214-ce4b1680-d0bb-11e9-9d13-ed06b50e8cc5.png)

**Comment by Apoorva-GA** [comment]
@zabil This seems to work for me. Could you please recheck this?

**Comment by Apoorva-GA** [comment]
Clicking on https://docs-preview.gauge.org/getting_started/installing-gauge.html?os=macos&language=javascript&ide=vscode#install-using-curl doesn't take to the right location.
