### ISSUE TITLE
Horizontal scroll not working for curl installation steps

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.gauge.org#263]
Installing Gauge -> Alternate installation methods -> Install using CURL

![Screenshot 2019-09-06 at 15 39 52](https://user-images.githubusercontent.com/54427/64436876-1f0f3f00-d0bd-11e9-8c52-d93fa1d939b5.png)

**Comment by BugDiver** [comment]
From #238

In the page

https://docs-preview.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#how-to-add-a-parameter

![Screenshot 2019-09-04 at 15 56 28](https://user-images.githubusercontent.com/54427/64266599-c1e48380-cf2c-11e9-8a2e-57771ae26281.png)

Two issues here.

* The the code block does not have a horizontal scroll when it overflows
* The copy button alignment is broken

**Comment by Apoorva-GA** [comment]
Also one more thing to look at is, the code block https://docs-preview.gauge.org/howto/ci_cd/docker.html?os=macos&language=javascript&ide=vscode#docker-image-for-gauge doesn't render properly.
