### ISSUE TITLE
Clarify that support for gauge_clear_state_level depends on language runner

### ISSUE THREAD

**Issue by F7502** [getgauge/docs.gauge.org#291]
The documentation at [https://docs.gauge.org/configuration.html](https://docs.gauge.org/configuration.html) describes the configuration parameter `gauge_clear_state_level` as if it were generally available in Gauge. However, it depends on the language runner if this parameter is respected during test execution or not. In `gauge-ts` as well as `gauge-js` this config parameter has no effect at all, in `gauge-java` it works as expected.

It would be good to have some hint in the documentation and maybe a list of language runners that are known to respect this configuration.

**Comment by shubhamsc** [comment]
@F7502 `gauge_clear_state_level` property specific to language. Currently, it does support only java and dotnet language runners.  I remove this property from `default.properties` and updated the docs as well. https://docs-preview.gauge.org/configuration.html

**Comment by F7502** [comment]
Great, thanks for clarifying that :-)
