### ISSUE TITLE
Install guide for linux > python > vscode somehow removed sources.list entries

### ISSUE THREAD

**Issue by es-m-se** [getgauge/docs.gauge.org#292]
Hi Guys,

New here, just tried to follow the install instructions here:
https://docs.gauge.org/getting_started/installing-gauge.html?os=linux&language=python&ide=vscode

It seems to have caused some issues for my PC, note the missing entries after the second 'apt-get update'.  I'm working on a new VM built from kubuntu-18.04.3-desktop-amd64.iso

shannon@ubuntu:~$ sudo apt-get update
[sudo] password for shannon: 
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]  
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                   
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 252 kB in 9s (27.2 kB/s)                                                                                                                                                   
Reading package lists... Done

shannon@ubuntu:~$ sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
Executing: /tmp/apt-key-gpghome.EMGShZ6VUH/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
gpg: key 25CCDC10023EDB0B: public key "gauge (gpg key for maven archetypes) <getgauge@thoughtworks.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

shannon@ubuntu:~$ echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee - a /etc/apt/sources.list
deb https://dl.bintray.com/gauge/gauge-deb stable main

shannon@ubuntu:~$ sudo apt-get update
Ign:1 https://dl.bintray.com/gauge/gauge-deb stable InRelease
Get:2 https://dl.bintray.com/gauge/gauge-deb stable Release [1,840 B]
Get:3 https://dl.bintray.com/gauge/gauge-deb stable Release.gpg [475 B]
Get:4 https://dl.bintray.com/gauge/gauge-deb stable/main i386 Packages [2,329 B]
Get:5 https://dl.bintray.com/gauge/gauge-deb stable/main amd64 Packages [2,329 B]
Fetched 6,973 B in 2s (4,126 B/s)
Reading package lists... Done

shannon@ubuntu:~$ sudo apt-get install gauge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  gauge
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,427 kB of archives.
After this operation, 19.2 MB of additional disk space will be used.
Get:1 https://dl.bintray.com/gauge/gauge-deb stable/main amd64 gauge amd64 1.0.6 [4,427 kB]
Fetched 4,427 kB in 4s (1,141 kB/s)             
Selecting previously unselected package gauge.
(Reading database ... 222720 files and directories currently installed.)
Preparing to unpack .../archives/gauge_1.0.6_amd64.deb ...
Unpacking gauge (1.0.6) ...
Setting up gauge (1.0.6) ...

We are constantly looking to make Gauge better, and report usage statistics anonymously over time. If you do not want to participate please read instructions https://manpage.gauge.org/gauge_telemetry_off.html on how to turn it off.

shannon@ubuntu:~$ sudo apt-get install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'curl' has no installation candidate
shannon@ubuntu:~$ sudo apt-get update
Ign:1 https://dl.bintray.com/gauge/gauge-deb stable InRelease
Get:2 https://dl.bintray.com/gauge/gauge-deb stable Release [1,840 B]
Fetched 1,840 B in 1s (1,651 B/s)
Reading package lists... Done
shannon@ubuntu:~$

**Comment by sriv** [comment]
hi, are you able to run `sudo apt-get install curl` without first running installing gauge on the virtual machine?

It seems from your logs that gauge got installed alright.

**Comment by es-m-se** [comment]
Hi Sriv,  

I think I see the problem: in the instructions the user is asked to run:
echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee - a /etc/apt/sources.list

...But there is a space between the '-' and the 'a'.  it should be '-a'.  As a result tee is overwriting the soruces.list file instead of appending to it.   

Side note:  Its more obvious but on the follow copy command it grabs two commands together that should probably be separate.

**Comment by sriv** [comment]
Yes, that's a good catch. I see that @nehashri has already [fixed the docs](https://github.com/getgauge/docs.gauge.org/commit/2a70fe9929bedc2c340954ff54d63b55241126f5). 

Thanks for the sidenote - I've [chained the two commands](https://github.com/getgauge/docs.gauge.org/commit/3876f30fa87e6110a388e85029fe3382b559a176), so copying should be fine now. 

We will publish the docs with the correction. Closing this issue for now.
