### ISSUE TITLE
.gauge folder details

### ISSUE THREAD

**Issue by callmekatootie** [getgauge/docs.gauge.org#299]
I observed that when running the tests, there is a .gauge folder created but the documentation makes no mention of this.

Furthermore, this folder seems to contain the `executionStatus.json` file, that contains the test run details - which I find to be useful. But the documentation does not speak about it.

**Comment by sriv** [comment]
Thanks for posting. In general the `.gauge` folder is a place for gauge to store state information that is required for a feature. Ex. `executionStatus.json` is used to display the execution status in editors like VSCode (using the gauge VScode plugin). In that context this is considered an implementation detail, and is subject to change. This means that there is no promise that this functionality will remain so in the future, and hence is not documented.

Hope this makes sense.

**Comment by callmekatootie** [comment]
That does make sense. Thank you.

Now, is there a similar file (such as `executionStatus.json`) that is reliable and has the same state info? I am running gauge inside docker and I wish to share the status of the execution (`gauge run specs` command) with the host. What would my best bet be

**Comment by sriv** [comment]
In that scenario, I think something like the [xml-report](https://github.com/getgauge/xml-report/) or [json-report](https://github.com/getgauge-contrib/json-report/) might suit you better.

**Comment by callmekatootie** [comment]
Yes it does. Thank you for pointing that out. I'll look into it.
