### ISSUE TITLE
Add documentation how to work with intellij

### ISSUE THREAD

**Issue by vasilievip** [getgauge/docs.gauge.org#315]
https://docs.gauge.org/getting_started/installing-gauge.html?os=macos&language=java&ide=vscode

Since gauge plugin is now supported by jetbains, could you please update docs and add IDEA into guides?

Thank you!

**Comment by zabil** [comment]
@vasilievip it will be easier to maintain in a README file https://github.com/JetBrains/intellij-plugins/tree/master/gauge

You can use the original README at https://github.com/getgauge/Intellij-Plugin/blob/master/README.md and send a pull request to https://github.com/JetBrains/intellij-plugins/tree/master/gauge

Please feel free to remove any copyright information and update the images.
