### ISSUE TITLE
dead link on examples

### ISSUE THREAD

**Issue by FlorianLudwig** [getgauge/docs.gauge.org#319]
The [examples page](https://docs.gauge.org/examples.html) links to:

Selenium With Page Objects / https://github.com/kashishm/gauge-example-python

Which is not available any more.

**Comment by sriv** [comment]
Thank you for highlighting this. 

On the topic of page objects, this blog tries to highlight why you need not use it when you use gauge : https://gauge.org/2017/06/13/the-page-objects-anti-pattern/

I will clean up the refernce.
