### ISSUE TITLE
Windows Installer links go to 1.4.3 version instead of the latest

### ISSUE THREAD

**Issue by cemerick1** [getgauge/docs.gauge.org#339]
The Windows Installer for Gauge is not on the current version and the CLI informs the user to go to the page to download the latest.

This attempts to install 1.4.3
![image](https://github.com/getgauge/gauge/assets/43388329/26ea962b-3b36-41ed-a0ba-702e02e7663d)

**Comment by sriv** [comment]
The site build deps have been updated and the latest build is deployed. it should have the right link for windows installer. Please check.

**Comment by chadlwilson** [comment]
Looks good, thanks @sriv !

**Comment by cemerick1** [comment]
Looks like it updated! Thanks @sriv @chadlwilson !
