### ISSUE TITLE
Provide examples for Concept

### ISSUE THREAD

**Issue by nehashri** [getgauge/docs.gauge.org#46]
Concepts section can have a small example on how a concept is defined and used.

**Comment by sguptatw** [comment]
@nehashri 
As on 24/09/2018, Concept documentation has an example and usage inside the step section of concepts.

![concepts](https://user-images.githubusercontent.com/6310197/45941599-94911500-bffc-11e8-8c64-abb411921fef.png)

Does this address the requirement or are you looking for something more?

**Comment by nehashri** [comment]
Yes it does.
