### ISSUE TITLE
Sections are missing help on where to go next 

### ISSUE THREAD

**Issue by suziejprince** [getgauge/docs.gauge.org#73]
This what Zabil said we should expect:

> A new user
> 
> * Lands on Gauge.org
> * Reads about features
> * Clicks “Get Started” button ti view “Get Started” page
> * Reads steps to install the Gauge binary, language runner, run tests 
> * Downloads and installs Gauge if interested
> * Sees our support for VS Code
> * Reads instructions on how to install Gauge Visual Studio Plugin
>     - Reads our welcome page inside VS code (this links to main documentation site) (exit) or
> * Clicks on a "Learn More" on the "Getting started" page. (display this at the end of the steps)
> * Views main documentation 
> * Reads installation for other options or to troubleshoot existing installation using the “Installation” section.  
> * Reads “Write Specifications”
> * **In each category of documentation we'll add a "What next?" and link to next steps for e.g on "Write Specifications" What next will be "Run Specifications"**
> * Reads "Run Specifications"
> 
> The "Get Started" link is always available on the top menu for those who land directly on the documentation page._
> 

But I don't see the "what's next?" links

**Comment by zabil** [comment]
Will not be adding the what's next feature for now.
