### ISSUE TITLE
Add docs for change in Python datastore API

### ISSUE THREAD

**Issue by nehashri** [getgauge/docs.gauge.org#89]

**Comment by BugDiver** [comment]
@nehashri  Isn't it addressed through https://github.com/getgauge/docs.gauge.org/commit/263315e6e76f89fafa5b19e2aaa285954118aefa?

**Comment by BugDiver** [comment]
Closing it since the docs are updated through  https://github.com/getgauge/docs.gauge.org/commit/263315e6e76f89fafa5b19e2aaa285954118aefa
